- hosts: localhost
  become: yes
  become_method: sudo
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present
      when: ansible_os_family == "Debian"

    - name: Install pip
      yum:
        name: python3-pip
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install virtualenv using apt
      apt:
        name: python3-virtualenv
        state: present
      when: ansible_os_family == "Debian"

    - name: Install virtualenv using yum
      yum:
        name: python3-virtualenv
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install python3-venv
      apt:
        name: python3-venv
        state: present
      when: ansible_os_family == "Debian"

    - name: Create a virtual environment
      command: python3 -m venv /home/user/venv

    - name: Install boto3 and botocore in virtual environment
      command: /home/user/venv/bin/pip install boto3 botocore

    - name: Add existing instance to host group
      add_host:
        hostname: "18.201.109.70"
        groupname: launched

    - name: Wait for SSH to come up
      wait_for:
        host: "18.201.109.70"
        port: 22
        delay: 60
        timeout: 320
        state: started
